import { useMutation } from '@tanstack/react-query';
import { Sparkles, RefreshCw } from 'lucide-react';
import { useState } from 'react';
import { apiGet } from '../lib/api';

// AnalyticsNarratorTile hits the CivicAI narrator endpoint and renders a
// plain-language digest of the same metrics shown on the Overview
// dashboard. Sits above the stat grid so operators see "what this means"
// before scanning "what the numbers are".
//
// On-demand generation: fresh calls cost money, and admin overview is a
// heavily-viewed page, so we don't auto-fire. Server-side Redis cache
// (15 min) means a second click within the window is essentially free.

interface Narration {
  scope: string;
  headline: string;
  narrative: string;
  highlights: string[];
  trends: string[];
  recommendations: string[];
  model: string;
  generatedAt: string;
  cached: boolean;
}

interface Envelope {
  narration: Narration;
}

interface ApiError {
  code?: string;
  message?: string;
}

export function AnalyticsNarratorTile() {
  const [narration, setNarration] = useState<Narration | null>(null);

  const mutation = useMutation({
    mutationFn: () =>
      apiGet<Envelope>('/api/v1/ai/narrate-metrics', { params: { scope: 'platform' } }),
    onSuccess: (data) => setNarration(data.narration),
  });

  const errorMsg = mutation.isError
    ? extractMessage(mutation.error) || 'CivicAI could not narrate metrics right now.'
    : null;

  return (
    <section className="admin-narrator-tile" aria-label="CivicAI analytics narrator">
      <header className="admin-narrator-header">
        <div className="admin-narrator-title-row">
          <span className="admin-narrator-icon" aria-hidden="true">
            <Sparkles size={16} />
          </span>
          <div>
            <h2 className="admin-narrator-title">CivicAI narrator</h2>
            <p className="admin-narrator-sub">Plain-language read on the platform numbers below.</p>
          </div>
        </div>
        <div className="admin-narrator-actions">
          {narration && (
            <span className="admin-narrator-cache-badge">
              {narration.cached ? 'Cached' : 'Fresh'}
            </span>
          )}
          <button
            type="button"
            className="admin-narrator-button"
            onClick={() => mutation.mutate()}
            disabled={mutation.isPending}
          >
            {mutation.isPending ? (
              'Generating…'
            ) : narration ? (
              <span className="admin-narrator-button-inner">
                <RefreshCw size={13} />
                Regenerate
              </span>
            ) : (
              'Narrate the numbers'
            )}
          </button>
        </div>
      </header>

      {errorMsg && <p className="admin-narrator-error">{errorMsg}</p>}

      {narration && (
        <div className="admin-narrator-body">
          <h3 className="admin-narrator-headline">{narration.headline}</h3>
          <p className="admin-narrator-narrative">{narration.narrative}</p>

          <div className="admin-narrator-grid">
            <NarratorList label="Highlights" items={narration.highlights} tone="civic" />
            <NarratorList label="Trends" items={narration.trends} tone="slate" />
          </div>

          <div className="admin-narrator-recs">
            <p className="admin-narrator-recs-label">Recommendations</p>
            <ol className="admin-narrator-recs-list">
              {narration.recommendations.map((r, i) => (
                <li key={i}>{r}</li>
              ))}
            </ol>
          </div>

          <footer className="admin-narrator-footer">
            <span>Generated by {narration.model}</span>
            <span className="admin-narrator-review-badge">AI-generated · review</span>
          </footer>
        </div>
      )}
    </section>
  );
}

function NarratorList({
  label,
  items,
  tone,
}: {
  label: string;
  items: string[];
  tone: 'civic' | 'slate';
}) {
  if (!items?.length) return null;
  return (
    <div>
      <p className="admin-narrator-list-label">{label}</p>
      <ul className={`admin-narrator-list admin-narrator-list-${tone}`}>
        {items.map((item, i) => (
          <li key={i}>{item}</li>
        ))}
      </ul>
    </div>
  );
}

function extractMessage(err: unknown): string | null {
  if (typeof err !== 'object' || err === null) return null;
  const anyErr = err as { response?: { data?: ApiError }; message?: string };
  return anyErr.response?.data?.message ?? anyErr.message ?? null;
}
