// Package gemini wraps the google.golang.org/genai SDK with the small,
// task-shaped surface CivicAI needs. Each civic feature (classify, summarize,
// draft) calls one method here rather than touching the SDK directly, so
// prompt strings, response-schema wiring, and default generation config
// stay in one place.
package gemini

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"google.golang.org/genai"
)

type Client struct {
	sdk   *genai.Client
	model string
}

// New constructs a Gemini client bound to a specific model. Fails hard at
// boot if the API key is rejected — better a loud crash than silent 500s
// on every AI call in production.
func New(ctx context.Context, apiKey, model string) (*Client, error) {
	sdk, err := genai.NewClient(ctx, &genai.ClientConfig{
		APIKey:  apiKey,
		Backend: genai.BackendGeminiAPI,
	})
	if err != nil {
		return nil, fmt.Errorf("gemini: init client: %w", err)
	}
	return &Client{sdk: sdk, model: model}, nil
}

// Model returns the configured model name — handlers echo this back in
// responses so the FE can display "Generated by gemini-2.5-flash".
func (c *Client) Model() string { return c.model }

// DefaultTimeout suits the interactive surfaces — a citizen classifying an
// issue as they type. Gemini flash is fast, but a slow tail can wedge the
// form, so fail fast and let the FE degrade gracefully.
const DefaultTimeout = 15 * time.Second

// GenerateJSON runs a single-turn generation and decodes the response as
// JSON into out. The system instruction pins tone + task; schema constrains
// the response shape so we never get free-form text back.
//
// out must be a pointer.
func (c *Client) GenerateJSON(
	ctx context.Context,
	systemInstruction, userPrompt string,
	schema *genai.Schema,
	out any,
) error {
	return c.GenerateJSONTimeout(ctx, DefaultTimeout, systemInstruction, userPrompt, schema, out)
}

// GenerateJSONTimeout is GenerateJSON with the deadline chosen by the caller.
//
// Not every surface has the same tolerance. Fifteen seconds is right when
// someone is mid-form and a slow answer is worse than no answer. It is wrong
// for a long prompt with a nested response schema being read by an admin who
// clicked a button and expects to wait — there, a timeout is a 502 on the
// work they actually came to do.
func (c *Client) GenerateJSONTimeout(
	ctx context.Context,
	timeout time.Duration,
	systemInstruction, userPrompt string,
	schema *genai.Schema,
	out any,
) error {
	ctx, cancel := context.WithTimeout(ctx, timeout)
	defer cancel()

	cfg := &genai.GenerateContentConfig{
		ResponseMIMEType: "application/json",
		ResponseSchema:   schema,
	}
	if systemInstruction != "" {
		cfg.SystemInstruction = &genai.Content{
			Parts: []*genai.Part{{Text: systemInstruction}},
		}
	}

	resp, err := c.sdk.Models.GenerateContent(
		ctx,
		c.model,
		[]*genai.Content{{
			Role:  "user",
			Parts: []*genai.Part{{Text: userPrompt}},
		}},
		cfg,
	)
	if err != nil {
		return fmt.Errorf("gemini: generate: %w", err)
	}

	text := resp.Text()
	if text == "" {
		return fmt.Errorf("gemini: empty response")
	}
	if err := json.Unmarshal([]byte(text), out); err != nil {
		return fmt.Errorf("gemini: parse json: %w (raw=%s)", err, text)
	}
	return nil
}
